version: 0.2

phases:
    install:
        commands:
            - dotnet workload install wasm-tools
    build:
        commands:
            - dotnet restore ./Source/IntelligenceReporting.sln
            - dotnet build -c Release ./Source/IntelligenceReporting.WebApi/IntelligenceReporting.WebApi.csproj
            - dotnet build -c Release ./Source/IntelligenceReporting.WebApp/IntelligenceReporting.WebApp.csproj
            - dotnet test -c Release ./Source/IntelligenceReporting.UnitTests/IntelligenceReporting.UnitTests.csproj
            - dotnet publish -c Release ./Source/IntelligenceReporting.WebApi/IntelligenceReporting.WebApi.csproj
            - dotnet publish -c Release ./Source/IntelligenceReporting.WebApp/IntelligenceReporting.WebApp.csproj             
artifacts:
  files:
    - './Source/IntelligenceReporting.WebApi/bin/Release/net6.0/publish/**/*'
    - './Source/IntelligenceReporting.WebApp/bin/Release/net6.0/publish/**/*'
    - './Source/IntelligenceReporting.Database/**/*'
    - './appspec.yml'
    - './codedeploy-beforeinstall.cmd'
    - './codedeploy-beforeinstall.sh'