MERGE INTO dbo.Source AS TARGET
USING (VALUES
    (1, 'VaultRE')
)
AS SOURCE (Id, SourceName)
ON TARGET.Id = SOURCE.Id
WHEN MATCHED THEN UPDATE SET
    TARGET.SourceName = SOURCE.SourceName
WHEN NOT MATCHED BY TARGET THEN
    INSERT (Id, SourceName)
    VALUES (Id, SourceName)
WHEN NOT MATCHED BY SOURCE THEN DELETE
;
